import { StyleSheet } from 'react-native';
import { Platform } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        backgroundColor: '#F07342',
        borderBottomLeftRadius: 32,
        borderBottomRightRadius: 32,
        flexDirection: 'column',
        gap: 16,
        alignItems: 'stretch',
        overflow: 'hidden',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.25,
        shadowRadius: 8,
        elevation: 6,
    }, 
    workspaceHeader: {
        width: '100%',
        flexDirection: 'row',
        paddingHorizontal: 32,
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    orderContainer: {
        flexDirection: 'row',
        paddingHorizontal: 32,
        paddingBottom: 16,
        gap: 24,
    },
    headerTitle: {
        fontFamily: 'Lexend',
        fontWeight: 400,
        fontSize: 20,
        color: '#EAE8E5',
        userSelect: 'none',
    },
    toggleContainer: {
        flexDirection: 'row',
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: '#EAE8E5',
        borderRadius: 12,
        padding: 4,
    },
    toggleButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        padding: 8,
        borderRadius: 8,
        userSelect: 'none',
    },
    activeToggleButton: {
        backgroundColor: '#EAE8E5',
    },
    inactiveToggleButton: {
        backgroundColor: 'transparent',
    },
    toggleText: {
        fontFamily: 'Lexend',
        fontWeight: 400,
        fontSize: 16,
    },
    activeToggleText: {
        color: '#333',
    },
    inactiveToggleText: {
        color: '#EAE8E5',
    },
    emptyContent: {
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 240,
        padding: 32,
        gap: 8,
    },
    emptyTitle: {
        fontFamily: 'Lexend',
        fontWeight: 500,
        fontSize: 18,
        color: '#EAE8E5',
    },
    emptySubtitle: {
        fontFamily: 'Lexend',
        fontWeight: 300,
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.8)',
        textAlign: 'center',
    },
    ticketWrapper: {
        justifyContent: 'center',
    },
    detailsContainer: {
        flex: 1,
        justifyContent: 'space-between',
        gap: 8,
    },
    recipeHeader: {
        gap: 4,
    },
    recipeTitleLabel: {
        fontFamily: 'Lexend',
        fontWeight: 500,
        fontSize: 20,
        color: '#EAE8E5',
    },
    selectedItemName: {
        fontFamily: 'Lexend',
        fontWeight: 300,
        fontSize: 16,
        color: '#EAE8E5',
    },
    recipeContent: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.12)',
        borderRadius: 8,
        padding: 16,
        gap: 8,
    },
    sectionSubTitle: {
        fontFamily: 'Lexend',
        fontWeight: 600,
        fontSize: 14,
        color: '#EAE8E5',
    },
    ingredientRow: {
        gap: 8,
    },
    ingredientText: {
        fontFamily: 'Lexend',
        fontWeight: 300,
        fontSize: 14,
        color: '#EAE8E5',
    },
    instructionsText: {
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: 300,
        color: '#EAE8E5',
    },
    noRecipeText: {
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: 300,
        color: 'rgba(255, 255, 255, 0.7)',
        fontStyle: 'italic',
    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 8,
    },
    timerBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    timerText: {
        fontFamily: 'Lexend',
        fontWeight: 400,
        fontSize: 26,
        color: '#EAE8E5',
    },
    buttonArea: {
        flexDirection: 'row',
        gap: 32,
    },
    button: {
        backgroundColor: '#EAE8E5',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 8,
        elevation: 6,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
    },
    buttonText: {
        fontFamily: 'Lexend',
        fontWeight: 400,
        color: '#F26E3B',
        fontSize: 16,
    },
});