import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        backgroundColor: '#F07342',
        borderBottomLeftRadius: 32,
        borderBottomRightRadius: 32,
        flexDirection: 'column',
        gap: 16,
        alignItems: 'stretch',
        overflow: 'hidden',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.25,
        shadowRadius: 8,
        elevation: 6,
    },
    content: {
        flexDirection: 'column',
        paddingHorizontal: 32,
        gap: 16,
    },
    sectionContent: {
        flexDirection: 'row',
        gap: 16,
        paddingBottom: 16,
    },
    ticketSection: {
        alignItems: 'flex-start',
    },
    sectionTitle: {
        fontSize: 20,
        fontFamily: 'Lexend',
        fontWeight: 400,
        color: '#EAE8E5',
    },
    formContainer: {
        flex: 1,
        justifyContent: 'flex-start',
        gap: 12,
    },
    label: {
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: 400,
        color: '#EAE8E5',
    },
    input: {
        backgroundColor: '#EAE8E5',
        borderRadius: 16,
        height: 48,
        paddingHorizontal: 16,
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: 400,
        color: '#303338',
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    flexInput: {
        flex: 1,
        gap: 8,
    },
    qtyInput: {
        maxWidth: 80,
        paddingHorizontal: 24,
        textAlign: 'center',
    },
    addButton: {
        flexDirection: 'row',
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        height: 48,
        paddingHorizontal: 16,
        borderRadius: 16,
        gap: 8,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.4)',
    },
    addButtonText: {
        color: '#EAE8E5',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: 400,
    },
    submitButton: {
        backgroundColor: '#303338',
        height: 48,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    submitButtonText: {
        color: '#EAE8E5',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: 400,
    },
});