import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  card: {
    width: 400,
    minHeight: 300,
    maxHeight: 600,
    backgroundColor: "#EAE8E5",
    borderRadius: 16,
    padding: 16,
    gap: 16,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitleGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  title: {
    fontFamily: "Lexend",
    fontSize: 16,
    fontWeight: "600",
    color: "#303338",
    textTransform: "capitalize",
  },
  label: {
    fontFamily: "Lexend",
    fontSize: 14,
    fontWeight: "500",
    color: "#303338",
  },
  input: {
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E0DDD9",
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontFamily: "Lexend",
    color: "#303338",
  },
  textArea: {
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E0DDD9",
    paddingHorizontal: 12,
    paddingVertical: 10,
    height: 120,
    textAlignVertical: "top",
    fontFamily: "Lexend",
    color: "#303338",
  },
  searchInput: {
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E0DDD9",
    padding: 12,
    fontFamily: "Lexend",
    color: "#303338",
  },
  formContainer: {
    flex: 1,
    justifyContent: "space-between",
    gap: 16,
    backgroundColor: 'red',
  },
  row: {
    flexDirection: "row",
    gap: 16,
  },
  flex1: {
    flex: 1,
    gap: 4,
  },
  roleSelectorGroup: {
    flexDirection: "row",
    gap: 16,
  },
  roleOptionBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: "center",
  },
  roleOptionSelected: {
    borderColor: "#F07342",
    backgroundColor: "#F0734215",
  },
  roleOptionUnselected: {
    borderColor: "#E0DDD9",
    backgroundColor: "#FFFFFF",
  },
  roleOptionText: {
    fontFamily: "Lexend",
    textTransform: "capitalize",
  },
  roleOptionTextSelected: {
    fontWeight: "600",
    color: "#F07342",
  },
  roleOptionTextUnselected: {
    fontWeight: "400",
    color: "#303338",
  },
  actions: {
    flexDirection: "row",
    gap: 16,
  },
  formActions: {
    flexDirection: "row",
    gap: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E0DDD9",
  },
  cancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E0DDD9",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  cancelText: {
    fontFamily: "Lexend",
    color: "#686B70",
    fontWeight: "500",
  },
  saveBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: "#F07342",
    alignItems: "center",
  },
  saveText: {
    fontFamily: "Lexend",
    color: "#FFFFFF",
    fontWeight: "600",
  },
  addBtn: {
    backgroundColor: "#F07342",
    borderRadius: 8,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  scrollGroup: {
    flex: 1,
    gap: 12,
  },
  scrollFlex: {
    flex: 1,
    gap: 12,
  },
  categoryCard: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 1,
  },
  categoryInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  categoryIconContainer: {
    backgroundColor: "#F0734215",
    padding: 8,
    borderRadius: 8,
  },
  categoryTitle: {
    fontFamily: "Lexend",
    fontWeight: "600",
    color: "#303338",
    fontSize: 16,
  },
  categoryCount: {
    fontFamily: "Lexend",
    color: "#686B70",
    fontSize: 12,
  },
  sectorCard: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 1,
  },
  sectorCardInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  sectorIconContainer: {
    backgroundColor: "#F0734215",
    padding: 8,
    borderRadius: 8,
  },
  sectorTitle: {
    fontFamily: "Lexend",
    fontWeight: "600",
    color: "#303338",
    fontSize: 16,
    textTransform: "capitalize",
  },
  sectorSubTitle: {
    fontFamily: "Lexend",
    color: "#686B70",
    fontSize: 12,
  },
  emptyText: {
    textAlign: "center",
    color: "#A09C9D",
    fontFamily: "Lexend",
  },
  employeeCard: {
    backgroundColor: "#FFFFFF",
    padding: 12,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  employeeName: {
    fontFamily: "Lexend",
    fontWeight: "500",
    color: "#303338",
    fontSize: 15,
  },
  employeeShift: {
    fontFamily: "Lexend",
    color: "#686B70",
    fontSize: 12,
  },
  employeeActionsGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  itemCard: {
    backgroundColor: "#FFFFFF",
    padding: 12,
    borderRadius: 8,
    gap: 10,
  },
  itemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  itemTitle: {
    fontFamily: "Lexend",
    fontWeight: "500",
    color: "#303338",
    fontSize: 15,
  },
  itemPrice: {
    fontFamily: "Lexend",
    color: "#686B70",
    fontSize: 12,
  },
  itemActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  recipeContainer: {
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#F0ECE9",
    gap: 4,
  },
  recipeTitle: {
    fontFamily: "Lexend",
    fontSize: 11,
    fontWeight: "600",
    color: "#F07342",
  },
  recipeText: {
    fontFamily: "Lexend",
    fontSize: 13,
    color: "#303338",
    lineHeight: 18,
  },
  iconBtn: {
    padding: 6,
    borderRadius: 6,
  },
  activeIconBtn: {
    backgroundColor: "#F0734220",
  },
});
