import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F07342',
    },
    content: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 16,
    },
    title: {
        fontFamily: 'Lexend',
        fontWeight: 400,
        fontSize: 24,
        color: '#EAE8E5',
        textAlign: 'center',
        paddingTop: 24,
    },
    optionsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: 24,
    },
    optionTitle: {
        fontFamily: 'Lexend',
        fontWeight: 400,
        fontSize: 18,
        color: '#FFFFFF',
        textAlign: 'center',
    },
    option: {
        width: 160,
        height: 140,
        borderRadius: 16,
        backgroundColor: '#EAE8E5',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    optionText: {
        fontFamily: 'Lexend',
        fontWeight: 300,
        fontSize: 18,
        color: '#F07342',
    },
    authContainer: {
        width: '100%',
        alignItems: 'center',
        gap: 16,
    },
    input: {
        width: '20%',
        height: 48,
        borderWidth: 1,
        borderColor: '#CCC',
        borderRadius: 8,
        paddingHorizontal: 16,
        fontSize: 16,
        backgroundColor: '#FFF',
    },
    errorText: {
        backgroundColor: '#EAE8E5',
        borderRadius: 8,
        padding: 8,
        fontFamily: 'Lexend',
        fontWeight: 500,
        color: '#D9383A',
        fontSize: 14,
    },
    Button: {
        backgroundColor: '#303338',
        paddingVertical: 12,
        paddingHorizontal: 32,
        borderRadius: 8,
    },
    ButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
});