export enum CategoryEnum {
  APPETIZER = 'APPETIZER',
  MAIN_COURSE = 'MAIN_COURSE',
  DESSERT = 'DESSERT',

  // Categorias reais do cardápio (Home Sushi Home)
  PROMOTION = 'PROMOTION',
  SHRIMP_SPECIALTY = 'SHRIMP_SPECIALTY',
  INDIVIDUAL_COMBO = 'INDIVIDUAL_COMBO',
  SHARED_COMBO = 'SHARED_COMBO',
  BUILD_YOUR_BOX = 'BUILD_YOUR_BOX',
  POKE = 'POKE',
  ASIAN_FOOD = 'ASIAN_FOOD',
  TEMAKI = 'TEMAKI',
  SPECIAL = 'SPECIAL',
  GENERAL = 'GENERAL',
}
