export enum OrderStateEnum {
    RECEIVED = 'RECEIVED',
    IN_PREPARATION = 'IN_PREPARATION',
    READY = 'READY',
    ON_THE_WAY = 'ON_THE_WAY',
    DELIVERED = 'DELIVERED',
    CANCELLED = 'CANCELLED'
}